channels:
    - conda-forge
    - astropy
dependencies:
    - matplotlib
    - numpy
    - scikit-learn
    - astropy
    - corner
    - pip
    - pip:
        - pystan
        - pygaia
        - daft
