channels:
- conda-forge
dependencies:
- jupyterlab=0.32.1
- nodejs=8.9
- notebook=5.4
- nbconvert=5.3
- ipykernel=4.7
- ipywidgets=7.2
- widgetsnbextension=3.2
- bqplot=0.10
- matplotlib=2.1
- pandas=0.20
- python=3.6
- sympy=1.0
- pyyaml
- traittypes==0.0.6
- invoke=0.21
- protobuf
- requests
- whoosh
- arrow