channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh=0.12
  - dask==0.18.2
  - dask-ml==0.9.0
  - distributed==1.22.1
  - numpy
  - pandas
  - pyarrow==0.9.0
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - py-xgboost
  - pip:
    - graphviz
    - dask_xgboost
    - seaborn
