name: geoist
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - impactutils
  - ipython
  - libcomcat
  - gdal
  - pip:
    - Cartopy
    - obspy
    - Shapely
    - scipy
    - pytest
    - pandas
    - h5py
    - numpy
    - pygmi
    - MarkDown
    - rasterio
    - kubernetes
