name: root
channels:
  - defaults
  - pyviz/label/dev
  - bokeh/label/dev
  - intake
  - conda-forge
dependencies:
  - conda-forge::proj4
  - jupyterhub==0.9.2
  - bokeh=0.12.16
  - bqplot
  - cython
  - cytoolz
  - cartopy
  - seaborn
  - dask=0.18.2
  - dask-ml
  - datashader
  - distributed=1.22.1
  - esmpy
  - fastparquet
  - gcsfs=0.1.2
  - ipywidgets
  - ipyleaflet
  - jupyter
  - jupyterlab=0.34.2
  - jupyterlab_launcher=0.13.1
  - jupyter_client
  - holoviews
  - libsodium
  - lz4
  - matplotlib=2.2.2
  - msgpack-python
  - nb_conda_kernels
  - netcdf4>1.4
  - nomkl
  - numba
  - numcodecs
  - numpy=1.15.1
  - pandas=0.23.2
  - python-blosc
  - pyzmq
  - s3fs
  - scipy
  - scikit-image
  - scikit-learn
  - toolz=0.9.0
  - tornado=5.0.2
  - xarray=0.10.8
  - zarr=2.2.0
  - zict
  - intake-xarray
  - graphviz
  - python-graphviz
  - gsw
  - pip:
    - fusepy
    - click
    - jedi
    - kubernetes==6.0.0
    - dask-kubernetes==0.5.0
    - xesmf
    - nbserverproxy==0.8.1
    - git+https://github.com/xgcm/xgcm
    - git+https://github.com/NicWayand/ESIO.git
