name: JupyterLab environment yml

channels:
  - default
  - damianavila82
  - conda-forge
dependencies: 
  - unidecode
  - jupyterlab=0.34.3
  - python=3.6.6
  - numpy=1.14.0
  - matplotlib=2.1.2
  - pandas=0.23.4 
  - IPython=6.2.1
  - altair=2.1.0 
  - seaborn=0.8.1  
  - scikit-learn=0.19.1  
  - ipywidgets
  - jupyter_contrib_nbextensions
  - xlrd=1.1.0
  
  