name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - bokeh
  - rise
  - jupyter_contrib_nbextensions
  - pip:
    - notebook==5.4.0
    - tensorflow==1.6.0
    - matplotlib==2.1.2
    - MIDIUtil==1.2.1
    - ipywidgets==7.2.0
    - numpy==1.14.2
    - scipy==1.0.0
    - Keras==2.1.5
    - seaborn==0.8.1
    - music21==5.1.0
    - ipython==6.4.0
    - scikit_learn==0.19.1
    - librosa==0.6.0