name: xarray
channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - netcdf4
  - ipywidgets
  - nbserverproxy
  - jupyterlab
