channels:
  - conda-forge
dependencies:
  - python=3
  - distributed=1.24
  - jupyterlab=0.35.1
  - numpy
  - pandas
  - basemap
  - cartopy
  - time
  - scikit-learn=0.20
  - matplotlib
  - xarray
  - pip:
    - graphviz
    - dask_xgboost
    - seaborn
    - mimesis