name: pygis-env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scikit-image
  - numpy
  - matplotlib
  - scipy
  - gdal
  - imageio
  - pip:
    - pygdal
    - lidar
    - tifffile
    - requests
    - googledrivedownloader
    - pygis
