name: pmagpy-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - future=0.16.0
  - numpy=1.14.0
  - matplotlib=2.2.2
  - pandas=0.23.1
  - basemap=1.1.0
  - basemap-data-hires=1.1.0
  - scipy=1.0.0
  - cartopy=0.16.0
  - pyqt=5.9.2
  - lmfit=0.9.11
  - scikit-learn=0.20.0
  - xlwt=1.2.0
#  - #cython                    0.28.5
  - pip:
    - pmagpy
    - pmagpy-cli
